# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - StdSampleApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://maelzayesandbox.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_65697dcb77ea4009a3f401a577dad20d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3ae2682503974e2187fe341f064dd6d3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: maelzayesandbox.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_65697dcb77ea4009a3f401a577dad20d }}/arc-sample-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'StdSampleApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6645e3ac0b8243e7977a0662c4c00b9c }}
        images: 'maelzayesandbox.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_65697dcb77ea4009a3f401a577dad20d }}/arc-sample-app:${{ github.sha }}'